[pytest]
# Tell pytest to look inside these specific python files or patterns for tests
python_files = 
    test_*.py 
    *_test.py 
    test.py
    app.py 
    scripts.py

# Tell pytest to look for functions starting with 'test_' or 'verify_'
python_functions = 
    test_* 
    verify_*
